
public enum EventType {
    CAR_SPAWN_L,
    CAR_SPAWN_R,
    CAR_AT_LIGHT,
    CAR_ACCELERATE,
    CAR_DECELERATE,
    CAR_REEVALUATE,
    CAR_STOP,
    CAR_CONSTANT,
    PED_SPAWN_L,
    PED_SPAWN_R,
    PED_AT_WALK,
    CAR_EXIT,
    PED_EXIT,
    BUTTON_PRESS,
    LIGHT_CHANGE
}
